/**
 * Supabase database type definitions.
 *
 * This file is auto-generated by running: npm run db:generate-types
 * Do not edit manually — run the generation script to update after schema changes.
 *
 * Until a live Supabase instance is connected, this provides the base types
 * matching the schema in supabase/migrations/00001_initial_schema.sql
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'super_admin' | 'chapter_lead' | 'content_editor' | 'coach' | 'public'
export type CertificationLevel = 'CALC' | 'PALC' | 'SALC' | 'MALC'
export type ContentStatus = 'draft' | 'published' | 'pending_approval' | 'rejected'
export type BlockType =
  | 'hero'
  | 'text'
  | 'image'
  | 'cta'
  | 'team_grid'
  | 'coach_list'
  | 'event_list'
  | 'testimonial'
  | 'faq'
  | 'contact_form'
  | 'stats'
  | 'video'
  | 'divider'
export type PaymentType =
  | 'enrollment_fee'
  | 'certification_fee'
  | 'membership_dues'
  | 'event_registration'
export type PaymentStatus = 'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded'
export type EventType =
  | 'workshop'
  | 'webinar'
  | 'conference'
  | 'certification'
  | 'networking'
  | 'other'

export interface Database {
  public: {
    Tables: {
      chapters: {
        Row: {
          id: string
          slug: string
          name: string
          country_code: string
          timezone: string
          currency: string
          accent_color: string
          logo_url: string | null
          is_active: boolean
          stripe_account_id: string | null
          contact_email: string | null
          website_url: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          country_code: string
          timezone?: string
          currency?: string
          accent_color?: string
          logo_url?: string | null
          is_active?: boolean
          stripe_account_id?: string | null
          contact_email?: string | null
          website_url?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['chapters']['Insert']>
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          phone: string | null
          role: UserRole
          chapter_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          role?: UserRole
          chapter_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      user_chapter_roles: {
        Row: {
          id: string
          user_id: string
          chapter_id: string
          role: UserRole
          granted_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          chapter_id: string
          role: UserRole
          granted_by?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_chapter_roles']['Insert']>
      }
      coach_profiles: {
        Row: {
          id: string
          user_id: string
          chapter_id: string | null
          certification_level: CertificationLevel
          bio: string | null
          specializations: string[]
          languages: string[]
          location_city: string | null
          location_country: string | null
          photo_url: string | null
          contact_email: string | null
          linkedin_url: string | null
          is_published: boolean
          is_verified: boolean
          certification_date: string | null
          recertification_due: string | null
          coaching_hours: number
          pending_changes: Json | null
          search_vector: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          chapter_id?: string | null
          certification_level: CertificationLevel
          bio?: string | null
          specializations?: string[]
          languages?: string[]
          location_city?: string | null
          location_country?: string | null
          photo_url?: string | null
          contact_email?: string | null
          linkedin_url?: string | null
          is_published?: boolean
          is_verified?: boolean
          certification_date?: string | null
          recertification_due?: string | null
          coaching_hours?: number
          pending_changes?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['coach_profiles']['Insert']>
      }
      pages: {
        Row: {
          id: string
          chapter_id: string | null
          slug: string
          title: string
          description: string | null
          is_published: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          chapter_id?: string | null
          slug: string
          title: string
          description?: string | null
          is_published?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['pages']['Insert']>
      }
      content_blocks: {
        Row: {
          id: string
          page_id: string
          block_type: BlockType
          content: Json
          sort_order: number
          is_visible: boolean
          status: ContentStatus
          published_version: Json | null
          draft_version: Json | null
          requires_approval: boolean
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          page_id: string
          block_type: BlockType
          content?: Json
          sort_order?: number
          is_visible?: boolean
          status?: ContentStatus
          published_version?: Json | null
          draft_version?: Json | null
          requires_approval?: boolean
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['content_blocks']['Insert']>
      }
      content_versions: {
        Row: {
          id: string
          content_block_id: string
          version_number: number
          content: Json
          status: ContentStatus
          changed_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          content_block_id: string
          version_number: number
          content: Json
          status: ContentStatus
          changed_by?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['content_versions']['Insert']>
      }
      events: {
        Row: {
          id: string
          chapter_id: string | null
          title: string
          description: string | null
          event_type: EventType
          start_date: string
          end_date: string | null
          timezone: string
          location_name: string | null
          is_virtual: boolean
          virtual_link: string | null
          max_attendees: number | null
          registration_url: string | null
          image_url: string | null
          is_published: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          chapter_id?: string | null
          title: string
          description?: string | null
          event_type?: EventType
          start_date: string
          end_date?: string | null
          timezone?: string
          location_name?: string | null
          is_virtual?: boolean
          virtual_link?: string | null
          max_attendees?: number | null
          registration_url?: string | null
          image_url?: string | null
          is_published?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['events']['Insert']>
      }
      payments: {
        Row: {
          id: string
          user_id: string
          chapter_id: string | null
          stripe_payment_intent_id: string | null
          stripe_checkout_session_id: string
          amount: number
          currency: string
          payment_type: PaymentType
          status: PaymentStatus
          receipt_url: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          chapter_id?: string | null
          stripe_payment_intent_id?: string | null
          stripe_checkout_session_id: string
          amount: number
          currency?: string
          payment_type: PaymentType
          status?: PaymentStatus
          receipt_url?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['payments']['Insert']>
      }
      audit_log: {
        Row: {
          id: string
          user_id: string | null
          action: string
          entity_type: string
          entity_id: string | null
          chapter_id: string | null
          old_value: Json | null
          new_value: Json | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          chapter_id?: string | null
          old_value?: Json | null
          new_value?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['audit_log']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      get_user_role: {
        Args: Record<string, never>
        Returns: UserRole
      }
      get_user_chapter_id: {
        Args: Record<string, never>
        Returns: string
      }
      user_has_chapter_role: {
        Args: { p_chapter_id: string; p_role: UserRole }
        Returns: boolean
      }
      is_super_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
      can_edit_chapter: {
        Args: { p_chapter_id: string }
        Returns: boolean
      }
      provision_chapter_pages: {
        Args: { p_chapter_id: string }
        Returns: undefined
      }
    }
    Enums: {
      user_role: UserRole
      certification_level: CertificationLevel
      content_status: ContentStatus
      block_type: BlockType
      payment_type: PaymentType
      payment_status: PaymentStatus
      event_type: EventType
    }
  }
}
